ctit085
	Adding nVidia Cuda Toolkit 11.8
	Adding nVidia cuDNN 8.8 (.1.3)
srun: Warning: can't run 1 processes on 2 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 2 nodes, setting nnodes to 1
2024-04-02 11:06:08.720422: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-04-02 11:06:09.261468: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-02 11:06:10.684350: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-04-02 11:06:11.022425: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-04-02 11:06:11.462730: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-02 11:06:12.827983: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Using the latest cached version of the dataset since mnist couldn't be found on the Hugging Face Hub
Loaded 168 configs, running...
Working directory in dataset: /home/s2240084/conFEDential
Working directory in MNIST: /home/s2240084/conFEDential
Traceback (most recent call last):
  File "/home/s2240084/conFEDential/src/batch_run_simulation.py", line 64, in <module>
    main()
  File "/home/s2240084/conFEDential/src/batch_run_simulation.py", line 60, in main
    run_simulation(config, client_resources, batch_run_name)
  File "/home/s2240084/conFEDential/src/run_simulation.py", line 127, in run_simulation
    train_loaders, test_loader = utils.load_data_loaders_from_config(config)
  File "/home/s2240084/conFEDential/src/utils/data.py", line 23, in load_data_loaders_from_config
    return dataclass.load_data(client_count, batch_size, preprocess_fn, alpha, percent_non_iid)
  File "/home/s2240084/conFEDential/src/federated_datasets/MNIST.py", line 38, in load_data
    train_dataset, test_dataset = load_dataset("mnist", cache_dir=".cache", split=["train", "test"])
  File "/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/datasets/load.py", line 2556, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/datasets/load.py", line 2265, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
  File "/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/datasets/packaged_modules/cache/cache.py", line 122, in __init__
    config_name, version, hash = _find_hash_in_cache(
  File "/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/datasets/packaged_modules/cache/cache.py", line 48, in _find_hash_in_cache
    raise ValueError(
ValueError: Couldn't find cache for mnist for config 'default'
Available configs in the cache: ['mnist']
Using the latest cached version of the dataset since mnist couldn't be found on the Hugging Face Hub
Loaded 168 configs, running...
Working directory in dataset: /home/s2240084/conFEDential
Working directory in MNIST: /home/s2240084/conFEDential
Traceback (most recent call last):
  File "/home/s2240084/conFEDential/src/batch_run_simulation.py", line 64, in <module>
    main()
  File "/home/s2240084/conFEDential/src/batch_run_simulation.py", line 60, in main
    run_simulation(config, client_resources, batch_run_name)
  File "/home/s2240084/conFEDential/src/run_simulation.py", line 127, in run_simulation
    train_loaders, test_loader = utils.load_data_loaders_from_config(config)
  File "/home/s2240084/conFEDential/src/utils/data.py", line 23, in load_data_loaders_from_config
    return dataclass.load_data(client_count, batch_size, preprocess_fn, alpha, percent_non_iid)
  File "/home/s2240084/conFEDential/src/federated_datasets/MNIST.py", line 38, in load_data
    train_dataset, test_dataset = load_dataset("mnist", cache_dir=".cache", split=["train", "test"])
  File "/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/datasets/load.py", line 2556, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/datasets/load.py", line 2265, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
  File "/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/datasets/packaged_modules/cache/cache.py", line 122, in __init__
    config_name, version, hash = _find_hash_in_cache(
  File "/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/datasets/packaged_modules/cache/cache.py", line 48, in _find_hash_in_cache
    raise ValueError(
ValueError: Couldn't find cache for mnist for config 'default'
Available configs in the cache: ['mnist']
srun: error: ctit088: task 0: Exited with exit code 1
srun: error: ctit085: task 0: Exited with exit code 1
