ctit088
2024-06-10 16:12:14,001	INFO usage_lib.py:412 -- Usage stats collection is enabled. To disable this, add `--disable-usage-stats` to the command that starts the cluster, or run the following command: `ray disable-usage-stats` before starting the cluster. See https://docs.ray.io/en/master/cluster/usage-stats.html for more details.
2024-06-10 16:12:14,001	INFO scripts.py:722 -- Local node IP: 10.20.240.18
Traceback (most recent call last):
  File "/home/s2240084/conFEDential/venv/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/ray/scripts/scripts.py", line 2474, in main
    return cli()
  File "/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/ray/autoscaler/_private/cli_logger.py", line 856, in wrapper
    return f(*args, **kwargs)
  File "/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/ray/scripts/scripts.py", line 742, in start
    raise ConnectionError(
ConnectionError: Ray is trying to start at 10.20.240.18:6379, but is already running at 10.20.240.18:6379. Please specify a different port using the `--port` flag of `ray start` command.
2024-06-10 16:13:02.313723: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-06-10 16:13:29.188091: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-10 16:14:07.547265: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
INFO flwr 2024-06-10 16:17:51,615 | Data.py:36 | Preprocessing the federated learning dataset
INFO flwr 2024-06-10 16:17:51,630 | Data.py:111 | Found preprocessed data for the given preprocess function with hash efddb1ca4fe67eba076ca51cfd1766212af1fce46847913eececd421a82a7a21, returning
Traceback (most recent call last):
  File "/home/s2240084/conFEDential/src/main.py", line 126, in <module>
    main()
  File "/home/s2240084/conFEDential/src/main.py", line 108, in main
    configs = batch_config.generate_configs_from_yaml_file(str(Path(args.yaml_file).resolve()), cache_root)
  File "/home/s2240084/conFEDential/src/utils/batch_config.py", line 79, in generate_configs_from_yaml_file
    configs = [Config.from_dict(raw_config, cache_root) for raw_config in raw_configs]
  File "/home/s2240084/conFEDential/src/utils/batch_config.py", line 79, in <listcomp>
    configs = [Config.from_dict(raw_config, cache_root) for raw_config in raw_configs]
  File "/home/s2240084/conFEDential/src/experiment/Config.py", line 44, in from_dict
    simulation=Simulation.from_dict(config['simulation'], cache_root),
  File "/home/s2240084/conFEDential/src/experiment/Simulation.py", line 61, in from_dict
    model=Model.from_dict(config['model'], cache_root)
  File "/home/s2240084/conFEDential/src/experiment/Model.py", line 65, in from_dict
    return Model(
  File "/home/s2240084/conFEDential/src/experiment/Model.py", line 30, in __init__
    self._prepare_model()
  File "/home/s2240084/conFEDential/src/experiment/Model.py", line 122, in _prepare_model
    model = self._load_model_from_hub(self._cache_root)
TypeError: Model._load_model_from_hub() takes 1 positional argument but 2 were given
srun: error: ctit088: task 0: Exited with exit code 1
2024-06-10 16:19:06.123660: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-06-10 16:19:06.192913: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-10 16:19:12.036662: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
INFO flwr 2024-06-10 16:19:26,089 | Data.py:36 | Preprocessing the federated learning dataset
INFO flwr 2024-06-10 16:19:26,090 | Data.py:111 | Found preprocessed data for the given preprocess function with hash efddb1ca4fe67eba076ca51cfd1766212af1fce46847913eececd421a82a7a21, returning
Traceback (most recent call last):
  File "/home/s2240084/conFEDential/src/main.py", line 126, in <module>
    main()
  File "/home/s2240084/conFEDential/src/main.py", line 108, in main
    configs = batch_config.generate_configs_from_yaml_file(str(Path(args.yaml_file).resolve()), cache_root)
  File "/home/s2240084/conFEDential/src/utils/batch_config.py", line 79, in generate_configs_from_yaml_file
    configs = [Config.from_dict(raw_config, cache_root) for raw_config in raw_configs]
  File "/home/s2240084/conFEDential/src/utils/batch_config.py", line 79, in <listcomp>
    configs = [Config.from_dict(raw_config, cache_root) for raw_config in raw_configs]
  File "/home/s2240084/conFEDential/src/experiment/Config.py", line 44, in from_dict
    simulation=Simulation.from_dict(config['simulation'], cache_root),
  File "/home/s2240084/conFEDential/src/experiment/Simulation.py", line 61, in from_dict
    model=Model.from_dict(config['model'], cache_root)
  File "/home/s2240084/conFEDential/src/experiment/Model.py", line 65, in from_dict
    return Model(
  File "/home/s2240084/conFEDential/src/experiment/Model.py", line 30, in __init__
    self._prepare_model()
  File "/home/s2240084/conFEDential/src/experiment/Model.py", line 122, in _prepare_model
    model = self._load_model_from_hub(self._cache_root)
TypeError: Model._load_model_from_hub() takes 1 positional argument but 2 were given
srun: error: ctit088: task 0: Exited with exit code 1
2024-06-10 16:19:31.096521: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-06-10 16:19:31.165518: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-10 16:19:34.352585: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
INFO flwr 2024-06-10 16:19:41,817 | Data.py:36 | Preprocessing the federated learning dataset
INFO flwr 2024-06-10 16:19:41,817 | Data.py:111 | Found preprocessed data for the given preprocess function with hash efddb1ca4fe67eba076ca51cfd1766212af1fce46847913eececd421a82a7a21, returning
Traceback (most recent call last):
  File "/home/s2240084/conFEDential/src/main.py", line 126, in <module>
    main()
  File "/home/s2240084/conFEDential/src/main.py", line 108, in main
    configs = batch_config.generate_configs_from_yaml_file(str(Path(args.yaml_file).resolve()), cache_root)
  File "/home/s2240084/conFEDential/src/utils/batch_config.py", line 79, in generate_configs_from_yaml_file
    configs = [Config.from_dict(raw_config, cache_root) for raw_config in raw_configs]
  File "/home/s2240084/conFEDential/src/utils/batch_config.py", line 79, in <listcomp>
    configs = [Config.from_dict(raw_config, cache_root) for raw_config in raw_configs]
  File "/home/s2240084/conFEDential/src/experiment/Config.py", line 44, in from_dict
    simulation=Simulation.from_dict(config['simulation'], cache_root),
  File "/home/s2240084/conFEDential/src/experiment/Simulation.py", line 61, in from_dict
    model=Model.from_dict(config['model'], cache_root)
  File "/home/s2240084/conFEDential/src/experiment/Model.py", line 65, in from_dict
    return Model(
  File "/home/s2240084/conFEDential/src/experiment/Model.py", line 30, in __init__
    self._prepare_model()
  File "/home/s2240084/conFEDential/src/experiment/Model.py", line 122, in _prepare_model
    model = self._load_model_from_hub(self._cache_root)
TypeError: Model._load_model_from_hub() takes 1 positional argument but 2 were given
srun: error: ctit088: task 0: Exited with exit code 1
2024-06-10 16:19:45,652	INFO scripts.py:1139 -- Did not find any active Ray processes.
